import React from "react";
import { navigate } from "@reach/router";
import { Formik, Field, Form } from "formik";

function AddTask() {
  const handleSubmit = values => {
    const requestTasks = async () => {
      // We get the CSRF token generated by Rails to send it
      // as a header in the request to create a new post.
      // This is needed because with this token, Rails is going to
      // recognize the request as a valid request
      const csrfToken = document.querySelector("meta[name=csrf-token]").content;
      const response = await fetch("/api/todo", {
        method: "POST",
        credentials: "include",
        headers: {
          "Content-Type": "application/vnd.api+json",
          "X-CSRF-Token": csrfToken
        },
        body: JSON.stringify({ data: values })
      });
      if (response.status === 201) {
        navigate("/");
      }
    };
    requestTasks();
  };

  return (
    <div>
      <h2>Add your task</h2>
      <Formik
        initialValues={{
          type: "todos",
          attributes: {
            body: "",
            status: "not-done",
            tag: ""
          }
        }}
        onSubmit={handleSubmit}
        render={() => (
          <Form>
            <Field type="text" name="attributes.body" placeholder="Description" />
            <Field type="text" name="attributes.tag" placeholder="Tag" />

            <button type="submit">Add</button>
          </Form>
        )}
      />
    </div>
  );
}

export default AddTask;