import React from "react";
import { navigate } from "@reach/router";
import { Formik, Field, Form } from "formik";

function AddTask() {
  const handleSubmit = values => {
    const requestTasks = async () => {
      // We get the CSRF token generated by Rails to send it
      // as a header in the request to create a new post.
      // This is needed because with this token, Rails is going to
      // recognize the request as a valid request
      const csrfToken = document.querySelector("meta[name=csrf-token]").content;
      const response = await fetch("/api/todo", {
        method: "POST",
        credentials: "include",
        headers: {
          "Content-Type": "application/vnd.api+json",
          "X-CSRF-Token": csrfToken
        },
        body: JSON.stringify({ data: values })
      });
      if (response.status === 201) {
        window.history.back();
      }
    };
    requestTasks();
  };

  return (
    <div>
      <h2>Add your task</h2>
      <Formik
          initialValues={{
            type: "todos",
            attributes: {
              body: "",
              status: "not-done",
              tag: ""
            }
          }}
          onSubmit={handleSubmit}
          >
          {(props) => (
            <form onSubmit={props.handleSubmit}>
            <label>Description:</label>
            <input type="text" name="attributes.body" onChange={props.handleChange} />
            <br />
            <label>Tag:</label>
            <input type="text" name="attributes.tag" onChange={props.handleChange} />
            <br />
            <button type="submit">Add</button>
            <button type="button" onClick={() => window.history.back()}>Go back</button>

            {props.errors.name && <div id="feedback">{props.errors.name}</div>}
          </form>
          )}
    </Formik>
    </div>
  );
}

export default AddTask;