import React from "react";
import { navigate } from "@reach/router";
import { Formik, Field, Form } from "formik";
import './main.css';

function DeleteTask(props) {
  const handleSubmit = values => {
    const requestTasks = async () => {
      // We get the CSRF token generated by Rails to send it
      // as a header in the request to create a new post.
      // This is needed because with this token, Rails is going to
      // recognize the request as a valid request
      const taskId = props.id;
      const csrfToken = document.querySelector("meta[name=csrf-token]").content;

      fetch("/api/todo/" + taskId, {
        method: "DELETE",
        credentials: "include",
        headers: {
          "Content-Type": "application/vnd.api+json",
          "X-CSRF-Token": csrfToken
        }
      });
      
      window.history.back();

    };
    requestTasks();
  };

  return (
    <div class="delete-task-container">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
      <h2 class="delete-task-header">Confirm Delete?</h2>
      <Formik
        initialValues={{
          type: "todos"
        }}
        onSubmit={handleSubmit}
      >
      {(props) => (
          <form onSubmit={props.handleSubmit}>
            <div class="delete-task-button">
              <button class="btn btn-outline-danger" type="submit">YES</button>
              <button class="btn btn-outline-success" type="button" onClick={() => window.history.back()}>NO</button>
            </div>
          </form>
      )}
      </Formik>
    </div>
  );
}

export default DeleteTask;