import React from "react";
import { navigate } from "@reach/router";
import { Formik, Field, Form } from "formik";

function DeleteTask() {
  const handleSubmit = values => {
    const requestTasks = async () => {
      // We get the CSRF token generated by Rails to send it
      // as a header in the request to create a new post.
      // This is needed because with this token, Rails is going to
      // recognize the request as a valid request
      const taskId = window.location.pathname.slice(8);
      const csrfToken = document.querySelector("meta[name=csrf-token]").content;

      fetch("/api/todo/" + taskId, {
        method: "DELETE",
        credentials: "include",
        headers: {
          "Content-Type": "application/vnd.api+json",
          "X-CSRF-Token": csrfToken
        }
      });
      
      window.history.back();

    };
    requestTasks();
  };

  return (
    <div>
      <h2>Confirm Delete?</h2>
      <Formik
        initialValues={{
          type: "todos"
        }}
        onSubmit={handleSubmit}
      >
      {(props) => (
          <form onSubmit={props.handleSubmit}>
            <button type="submit">YES</button>
            <button type="button" onClick={() => window.history.back()}>NO</button>
          </form>
      )}
      </Formik>
    </div>
  );
}

export default DeleteTask;