import React from "react";
import { navigate } from "@reach/router";
import { Formik, Field, Form } from "formik";

function DoneTask() {
  const handleSubmit = () => {
    const requestTasks = async () => {
      // We get the CSRF token generated by Rails to send it
      // as a header in the request to create a new post.
      // This is needed because with this token, Rails is going to
      // recognize the request as a valid request
      const taskId = window.location.pathname.slice(5);
      
      const csrfToken = document.querySelector("meta[name=csrf-token]").content;

      fetch("/api/todo/" + taskId, {
        method: "PATCH",
        credentials: "include",
        headers: {
          "Content-Type": "application/vnd.api+json",
          "X-CSRF-Token": csrfToken
        },
        body: JSON.stringify({ attributes: {status: "done"}})
      });
      

      return navigate('/');

    };
    requestTasks();
  };

  handleSubmit();
}

export default DoneTask;