import React from "react";
import { navigate } from "@reach/router";
import { Formik, Field, Form } from "formik";

function DoneTask() {
  const handleSubmit = () => {
    const requestTasks = async () => {
      // We get the CSRF token generated by Rails to send it
      // as a header in the request to create a new post.
      // This is needed because with this token, Rails is going to
      // recognize the request as a valid request
      const taskId = window.location.pathname.slice(6);
      console.log(taskId);
      const csrfToken = document.querySelector("meta[name=csrf-token]").content;

      const response = await fetch("/api/todo/" + taskId, {
        method: "PATCH",
        credentials: "include",
        headers: {
          "Content-Type": "application/vnd.api+json",
          "X-CSRF-Token": csrfToken,
        },
        body: JSON.stringify({
          data: {id: taskId, type: "todos", attributes: {status: "done"}}
        })
      });
      
      if (response.status === 200) {
        window.history.back();
      }
    };
    requestTasks();
  };

  handleSubmit();
  return <div>Completed</div>;
}

export default DoneTask;